[gspread]
type = "service_account"
project_id = "yemek-kalori-ai"
private_key_id = "40a0ac484bc5abed1e12cf06450b02b912f3ce0f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCiAoU5yhHzkLb6
bObbcsvZgqKs1lzZeRIDAyrng3DkH9VJa667pdzdcN0Yyg1k5uOs7c2UjWUeBd90
nfaw1zwuFxhgb2cCi5vX15TwIHAW/7GtdVr1H537vkS0tUW9FPaRLq+S+qgneXTi
TskkhtpPRq7RlFulXT4Y5b+VRe+r5WD1+PM7nP8y9Dqdegeu5Z5lvbOqf3QCkn6N
X0oKyZI1jKt5jhOOouq6gVd5VAg8GLR/A5QrzFkYS8BSJMIJCWGJPfQEJZU9HnBv
5tRLfm0lnDcJVdrmsbHX/4A803AB0YP94Pr0NjNJH8s33Pa4LxqSwLG5wnGoeQ3k
wF5TgyCHAgMBAAECggEATSGZDxHa6RSJYQGvCWSGk9hDnbjy/KDNB/0elJl6Cknz
kCCB0JnfZNgCk3ZC2Tqpw592BFcrAJe4MruwArJ+Vs0tEGCJcOdJu4HKSWaQJwr2
KwiX1OMIIp4L9OLmwGY2G5nYAkhu/VgwYzwyPD8tuZeDzIju9vRFB7J+O1HQEQyC
P8z6LQYUikNjS3IZocKARJo3oD/O61Ue5I11KwPPsMuxXkHbYukNREpE+pk/siJF
MjCGvlMCrrzrV65Z0DbV+Bm3p0FkvYYYkMxCDCPvlCAedmky4yzTjr1Zd3zjg8z6
ZaaOxdG4vRYAPGF3yoz56XtWA5hyEN3vunWnMHxU0QKBgQDUNiAZk6AY1nK9YqCc
Jkz75EEa6U4yVWMcVL1LJt2arkJJByYHDw2oQ55lEyg7KwcvFySvtUtEFPbuZfFR
RhGwUw92CAaVvWkhOjxx1aelhrfPGa3h92xAetKy+5U19QAqzRtY/lJPjBtE0ryG
fdXDZjEUhOWvIaQ8ayCjXK600QKBgQDDcIrYCjRkXNv1TKAu5cv74AFfPWAtk+47
bYWQf/z+gGp79srFZvPz/uEyckNUbejNa0ULx/3Wz5Zb1+nEIBDAiNWmMT8Q96if
yPumUHVWq3Ge/VtSQrhIVvoixzpBcfDwaTE1q9zvhJAjYI4UuGqoK+o19nlQJWI4
0qE/Ojo11wKBgHHqDBkuscYjd7xJ8UVhGfotcPVtP9itFWLj6ikpV9PsrxBckgFA
B2jHw4MmYXZBhr20grD/dMO7LUKT3pJuNpicPbRyYnaHEqQPitrggfnM82ZstnaS
Rr3mMKx7eIFaXxiauY9wFec1on2zUhgv/EvD05zcKh90w6DbMM4AtpfBAoGAVO/a
R53Xuy5oIalVjEwuZJ6rufpwjB5YUNd+TphxGSIyJQHSigv+RbIlqMjj3hOOM4hF
D6Ow++Rn0i5519Sfsy1EvN92KyeWzyqHw3YAKNSForU1NQDuGfJC705qUPr13WW6
DztL34RbKCTUWsjzAXdkaGNfwacdkthnX5Usqy0CgYBpxjNnJAVBpjahdOtTCy1r
bkSLo/694JUfgSO73UslhQElDUJrTT7reB0PT0kpoFgPmR9iH//zqJLZ0j1HW2BK
UtwaA1KMMKzW+hZrldtJWNc3Tj7q18E3rqYMPhIiqk1+OKn6NkGRNxNMhv21ORT9
y7eWlsEULtGcgGwkWfAWOw==
-----END PRIVATE KEY-----"""
client_email = "kalori-kayitci@yemek-kalori-ai.iam.gserviceaccount.com"
client_id = "114967692089640286018"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/kalori-kayitci%40yemek-kalori-ai.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
